@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
'https://plantuml.com/activity-diagram-beta

start
:User enters add command;
if (Valid details?) then (yes)
    :Add person;
    stop
else (no)
    :throw exception;
    stop
endif

@enduml
